export enum Color {
  PRIMARY_MAIN = "#7B61FF",
  PRIMARY_SUB = "#917CFF",
  SECONDARY = "var(--color-secondary)",
  BLACK = "#000000",
  DARK = "var(--color-dark-sub)",
  GRAPHITE = "var(--color-graphit)",
  ERROR = "#FF5154",
  LIGHT = "#AFB2B6",
  WHITE = "var(--color-white)",
  GREEN = "#00A340",
  YELLOW = "#F3A608",
  ORANGE = "#F45D2D",
  BACKROUND = "var(--color-dark)",
}
